version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    groups:
      maven-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    groups:
      node-build-image:
        patterns: ["node"]
      java-lts-images:
        patterns: ["eclipse-temurin"]
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]
