version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    groups:
      maven-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    groups:
      node-build-image:
        patterns: ["node"]
      maven-build-image:
        patterns: ["maven"]
      java-runtime-image:
        patterns: ["eclipse-temurin"]
